Repository canonical/charmed-kubeflow.io, pull requests merged in 2020-11, with the labels that each got.

#26 Update the brand colour to Ubuntu orange
  static/sass/_settings.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#28 Copy update on charmed kubeflow homepage
  templates/index.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#29 Remove terser, fix postcss, fix discourse link
  package.json
  templates/partial/_navigation.html
  webpack.config.js
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#31 Fixup page titles
  templates/base_layout.html
  templates/contact-us.html
  templates/docs/document.html
  templates/index.html
  templates/thank-you.html
Labels: Review: Code +1, Review: QA +1

#33 Update to charmhub.io link
  templates/index.html
Labels: Review: Code +1, Review: QA +1
