Repository canonical/charmed-kubeflow.io, pull requests merged in 2020-09, with the labels that each got.

#2 Fix Sentry DSN
  konf/site.yaml
Labels: Review: Code +1

#1 Fix the name typo
  .github/pull_request_template.md
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/contact-us.html
  templates/thank-you.html
  webapp/app.py
Labels: Review: Code +1

#4 Update port PR workflow
  .github/workflows/pr.yml
Labels: Review: Code +1

#3 Build the dynamic content form
  .prettierignore
  .prettierrc
  static/js/dynamic-contact-form.js
  templates/base_layout.html
  templates/contact-us.html
  templates/docs/search.html
  templates/includes/contact-us.html
  templates/index.html
  templates/thank-you.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#10 Change the discourse and docs links
  templates/partial/_navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#11 Use smaller hero image
  templates/base_layout.html
  templates/index.html
Labels: Review: Code +1, Review: Design +1

#9 Apply copy updates
  templates/index.html
Labels: Review: Code +1

#12 Update the hero image
  templates/index.html
Labels: Review: Design +1

#13 Remove category argument
  .github/workflows/pr.yml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#14 Fix non-sequential headings
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#17 Fix lighthouse SEO issues
  templates/base_layout.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#18 Update flask-base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#19 Remove unnecessary markup from contact form
  templates/includes/contact-us.html
Labels: Review: Code +1, Review: QA +1
