Repository canonical/charmed-kubeflow.io, pull requests merged in 2022-11, with the labels that each got.

#121 Update navigation with new branding
  package.json
  static/js/global-nav.js
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: PdM +1

#139 Implement expandable side-nav and search for /docs
  requirements.txt
  static/js/side-navigation.js
  templates/docs/document.html
  templates/docs/search.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#140 Update konf to inc google search key
  konf/site.yaml
Labels: Review: Code +1, Review: QA +1
